@isTest
public class BA1Test {
    public static testMethod void anyName(){
        BA1.getCount();
        BA1 b_1 = new BA1();
        b_1.getValues();
        BA1.getCount();
        BA1 b_2 = new BA1('Raj',123,10000);
        b_2.getvalues();
        BA1.getCount();
        BA1 b_3 = new BA1('Dell',456,20000);
        b_3.getvalues();
        BA1.getCount();
        BA1 b_4 = new BA1('Sony',789,30000);
        b_4.getvalues();
        BA1.getCount();
        
    }

}