public class CustomLabelWrapper {
	public Integer size;	//19
	public Integer totalSize;	//19
	public boolean done;
	public String entityTypeName;	//ExternalString
	public List<cls_records> records;
	public class cls_records {
		public cls_attributes attributes;
		public String Name;	//Created_by_Me
	}
	public class cls_attributes {
		public String type;	//ExternalString
		public String url;	///services/data/v59.0/tooling/sobjects/ExternalString/1015i00000K7VSsAAN
	}
}