@isTest
public class PracticeRectangleTest {
    public static testMethod void anyName(){
        PracticeRectangle.getcount();
        PracticeRectangle a = new PracticeRectangle();
        PracticeRectangle.getcount();
        PracticeRectangle b = new PracticeRectangle();
        PracticeRectangle.getcount();
        PracticeRectangle c = new PracticeRectangle();
        PracticeRectangle.getcount();
        PracticeRectangle aa = new PracticeRectangle('Laptop',1234,10000);
        PracticeRectangle.getcount();
        PracticeRectangle bb = new PracticeRectangle('Mobile',5678,20000);
        PracticeRectangle.getcount();
        PracticeRectangle cc = new PracticeRectangle('Board',1122,30000);
        PracticeRectangle.getcount();
        
 }

}