@isTest
public class RectangleTest {
    public static testMethod void anyName(){
        Rectangle board = new Rectangle();
        board.setValues(10,20);
        board.getValues();
        /*Integer ar_board = board.calcArea();
        Integer pr_board = board.calcPermeter();
        System.debug('Area of board is ' + ar_board);
        System.debug('Perimeter of board is ' + pr_board);*/
        /*Rectangle laptop = new  Rectangle(30,40);
        //laptop.setValues(30,40);
        Integer ar_laptop = laptop.calcArea();
        Integer pr_laptop = laptop.calcPermeter();
        System.debug('Area of laptop is ' + ar_laptop);
        System.debug('Perimeter of laptop is ' + pr_laptop);*/
        
        
    }

}