public class TopLevelClass{
    public class InnerClass{
    public void innerClassMtd(){//Non-Static
        System.debug('Hello Computing World');
    }
      /*public static void innerClassStaticMtd(){//Static
    
      }*/  
    
    }
    
     public interface InnerInterface{
         //void SayGoodBye();
         void innerInterfaceMtd1();
         //void SayGetLost();
         void innerInterfaceMtd2();
         
     }
         
        
     }